site_name: MasterMind API
repo_url: https://github.com/martel-innovate/MasterMind-API
site_description: MasterMind API Documentation
docs_dir: 'docs'
theme: readthedocs
pages:
    - Home: 'index.md'
    - Quick Start: 'quickstart.md'
    - Architecture: 'architecture.md'
    - User Manual:
        - 'Introduction': 'user/introduction.md'
    - Installation & Administration Manual:
        - 'Introduction': 'admin/introduction.md'
        - 'Installation': 'admin/installation.md'
        - 'Configuration': 'admin/configuration.md'
